name: Test SuperDMZ

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:

      - name: Install SuperDMZ
        run: |
          curl -fsSL https://superdmz.com/download/LinuxInstaller.sh | sudo sh

      - name: Show Help
        run: |
          echo "========== VERSION =========="
          sudo superdmz-client -version

          echo ""
          echo "========== HELP =========="
          sudo superdmz-client -h || true

          echo ""
          echo "========== STATE =========="
          sudo superdmz-client -state

          echo ""
          echo "========== STATUS =========="
          sudo superdmz-client -status
